# Generated by Django 3.1.7 on 2021-04-21 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacts'},
        ),
    ]
